"""Write the API section of each per-model page from the package's docstrings.

Run it with `uv run python tools/build_model_pages.py`. Each page under
`docs/models/` is hand-written except for the block below its API marker, which
this replaces. A test fails when a page on disk stops matching, so a changed
signature cannot ship beside a stale page.

The mapping is not kept here. `release.toml` already declares the entry points
of every supported analysis, and this reads them, so a model that gains a
method gains it on its page without anyone remembering to.
"""

from __future__ import annotations

import argparse
import inspect
import tomllib
from pathlib import Path
from typing import Any

import asterism

ROOT: Path = Path(__file__).resolve().parents[1]
"""Located the repository root holding the pages and the manifest."""

MARKER: str = "<!-- API: generated by tools/build_model_pages.py -->"
"""Marked where the generated block begins. Everything above it is written."""

SLUGS: dict[str, str] = {
    "one_trait_gaussian_heritability": "one-trait",
    "several_covariance_components": "several-components",
    "bivariate_genetic_correlation": "two-traits",
    "continuous_gene_by_environment": "gxe-measured",
    "discrete_gene_by_environment": "gxe-binary",
    "binary_liability_heritability": "binary",
    "one_trait_censored": "censored",
    "mixed_binary_censored_genetic_correlation": "mixed",
}
"""Named the page each analysis writes to."""


def resolve(path: str) -> Any:
    """Follow a dotted entry point such as ``asterism.ComponentModel.fit``.

    Args:
        path: The entry point as the manifest declares it.

    Returns:
        Whatever it names.
    """
    obj: Any = asterism
    """Started from the package itself."""

    for part in path.split(".")[1:]:
        obj = getattr(obj, part)
        """Walked one step along the dotted path."""
    return obj


def signature_of(obj: Any) -> str:
    """Render one callable's signature, or an empty string if it has none.

    Args:
        obj: A function, method or class.

    Returns:
        The signature in parentheses, or "".
    """
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return ""


def rendered(analysis: dict[str, Any]) -> str:
    """Build the API section for one analysis from its entry points.

    Args:
        analysis: One analysis table from the release manifest.

    Returns:
        The Markdown to place below the marker.
    """
    lines: list[str] = [MARKER, "", "## Interface", ""]
    """Opened the generated block with the heading it owns."""

    lines.append(
        "Generated from the package's own docstrings. The complete public "
        "surface is in the [API reference](../api-reference.md).\n"
    )
    for path in analysis["entry_points"]:
        obj: Any = resolve(path)
        """Read one declared entry point."""

        signature: str = signature_of(obj)
        """Rendered its signature, or nothing where it has none."""

        lines.append(f"### `{path.removeprefix('asterism.')}{signature}`\n")
        lines.append(inspect.cleandoc(obj.__doc__ or "No documentation.") + "\n")
    return "\n".join(lines)


def main() -> int:
    """Write every page's API section, or check the ones on disk match.

    Returns:
        Zero when every page is correct or was written, one when any is stale.
    """
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description=__doc__.splitlines()[0]
    )
    """Built the one-flag command line."""

    parser.add_argument("--check", action="store_true")
    arguments: argparse.Namespace = parser.parse_args()
    """Read whether this run writes or only checks."""

    manifest: dict[str, Any] = tomllib.loads(
        (ROOT / "release.toml").read_text(encoding="utf-8")
    )
    """Read the analyses and their declared entry points."""

    stale: list[str] = []
    """Collected every page whose generated block is out of date."""

    for analysis in manifest["analyses"]:
        slug: str = SLUGS[analysis["id"]]
        """Named the page this analysis writes to."""

        page: Path = ROOT / "docs" / "models" / f"{slug}.md"
        """Located it."""

        current: str = page.read_text(encoding="utf-8")
        """Read what is there now."""

        head: str = current.split(MARKER)[0]
        """Kept everything a person wrote above the marker."""

        wanted: str = head + rendered(analysis) + "\n"
        """Built what the page should be."""

        if arguments.check:
            if current != wanted:
                stale.append(slug)
        else:
            page.write_text(wanted, encoding="utf-8")
    if arguments.check:
        if stale:
            print(f"stale model pages: {', '.join(stale)}")
            print("run tools/build_model_pages.py")
            return 1
        return 0
    print(f"wrote {len(manifest['analyses'])} model pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
