"""Shared mechanics for strict native-SOLAR reference adapters.

Scientific inputs, Asterism calls and acceptance rules remain in each adapter.
This module provides only deterministic hashing, exact native-SOLAR identity,
fixture loading and the optional two-mode command-line contract. Every SOLAR
fixture hashes this source so a mechanics change makes portable verification
fail closed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import subprocess
from datetime import datetime
from pathlib import Path

import numpy as np

CONTRACT_VERSION: int = 1
"""Matched the strict envelope contract in external_reference_fixture.py."""

HASH_DECIMALS: int = 12
"""Removed irrelevant last-bit drift from generated floating-point inputs."""

SOLAR_EXECUTABLE: Path = Path("/usr/local/bin/solar")
"""Pinned refreshes to the qualified native executable rather than PATH."""

QUALIFIED_SOLAR_VERSION: str = "SOLAR Eclipse 9.0.0 (2022-01-01)"
"""Named the independently installed SOLAR release qualified for fixtures."""

QUALIFIED_SOLAR_TOOLS: list[dict[str, object]] = [
    {
        "name": SOLAR_EXECUTABLE.as_posix(),
        "version": QUALIFIED_SOLAR_VERSION,
        "packages": [],
    }
]
"""Recorded the complete expected external-tool identity."""


class SolarReferenceError(ValueError):
    """Report a missing tool, malformed fixture or incomplete SOLAR output."""


def parse_reference_arguments(description: str) -> argparse.Namespace:
    """Parse strict fixture mode while preserving historical no-argument use.

    Args:
        description: Module documentation displayed by ``--help``.

    Returns:
        Arguments with both reference fields present or both absent.

    Raises:
        SystemExit: If only one strict-reference argument is supplied.
    """
    parser: argparse.ArgumentParser = argparse.ArgumentParser(description=description)
    """Extended each live check with two explicit, paired fixture options."""

    parser.add_argument("--reference-mode", choices=("refresh", "verify"))
    parser.add_argument("--reference-fixture", type=Path)
    arguments: argparse.Namespace = parser.parse_args()
    """Parsed no positional arguments so the historical invocation remains valid."""

    if (arguments.reference_mode is None) != (arguments.reference_fixture is None):
        parser.error(
            "--reference-mode and --reference-fixture must be supplied together"
        )
    return arguments


def canonical_json_bytes(value: object) -> bytes:
    """Return deterministic finite JSON bytes for a generated input.

    Args:
        value: JSON-compatible participant-free input description.

    Returns:
        Stable UTF-8 representation without insignificant whitespace.

    Raises:
        SolarReferenceError: If the value is not finite canonical JSON.
    """
    try:
        rendered: str = json.dumps(
            value,
            allow_nan=False,
            ensure_ascii=True,
            separators=(",", ":"),
            sort_keys=True,
        )
        """Rendered a platform-independent scalar or structured input."""
    except (TypeError, ValueError) as error:
        raise SolarReferenceError(
            f"input is not finite canonical JSON: {error}"
        ) from error
    return rendered.encode("utf-8")


def json_identity(name: str, value: object) -> dict[str, str]:
    """Identify one canonical generated input by SHA-256.

    Args:
        name: Stable human-readable input name.
        value: JSON-compatible participant-free input.

    Returns:
        Strict fixture identity record.
    """
    digest: str = hashlib.sha256(canonical_json_bytes(value)).hexdigest()
    """Hashed exact canonical content rather than Python object identity."""

    return {"name": name, "sha256": digest}


def bytes_identity(name: str, value: bytes) -> dict[str, str]:
    """Identify exact generated file content by SHA-256.

    Args:
        name: Stable human-readable input name.
        value: Exact participant-free generated bytes.

    Returns:
        Strict fixture identity record.
    """
    digest: str = hashlib.sha256(value).hexdigest()
    """Hashed the generated bytes without a JSON or platform text transformation."""

    return {"name": name, "sha256": digest}


def array_identity(name: str, value: np.ndarray) -> dict[str, str]:
    """Identify one generated numeric array in a stable representation.

    Args:
        name: Stable human-readable input name.
        value: Participant-free generated array.

    Returns:
        Strict identity including scalar type, shape and canonical values.

    Raises:
        SolarReferenceError: If values are non-finite or the dtype is unsupported.
    """
    array: np.ndarray = np.asarray(value)
    """Accepted any NumPy view without trusting memory order or byte order."""

    if np.issubdtype(array.dtype, np.floating):
        if not np.all(np.isfinite(array)):
            raise SolarReferenceError(f"generated input {name!r} is non-finite")
        normalised: np.ndarray = np.round(array.astype("<f8"), HASH_DECIMALS)
        """Quantised harmless last-bit platform drift before exact hashing."""
    elif np.issubdtype(array.dtype, np.integer):
        normalised = array.astype("<i8")
        """Normalised integer width and byte order across Mac and Linux."""
    elif np.issubdtype(array.dtype, np.bool_):
        normalised = array.astype("|b1")
        """Represented Boolean masks as one byte per exact status value."""
    else:
        raise SolarReferenceError(
            f"generated input {name!r} has unsupported dtype {array.dtype}"
        )

    header: bytes = canonical_json_bytes(
        {"dtype": normalised.dtype.str, "shape": list(normalised.shape)}
    )
    """Bound otherwise identical values to their semantic shape and scalar type."""

    payload: bytes = (
        header + b"\0" + np.ascontiguousarray(normalised).tobytes(order="C")
    )
    """Combined the semantic header and canonical contiguous array bytes."""

    digest: str = hashlib.sha256(payload).hexdigest()
    """Compressed the complete stable representation into one identity."""

    return {"name": name, "sha256": digest}


def support_source_identity() -> dict[str, str]:
    """Identify these shared SOLAR mechanics for stale-fixture detection.

    Returns:
        Strict identity record for this exact source file.
    """
    source: Path = Path(__file__).resolve()
    """Resolved the imported helper rather than trusting the working directory."""

    digest: str = hashlib.sha256(source.read_bytes()).hexdigest()
    """Bound fixtures to the canonicalisation and tool-version mechanics used."""

    return {"name": "source:checks/solar_reference_adapter.py", "sha256": digest}


def load_fixture(path: Path, check_id: str) -> dict[str, object]:
    """Load the frozen envelope for portable adapter verification.

    Args:
        path: Versioned fixture written by the strict driver.
        check_id: Adapter's fixed manifest check identifier.

    Returns:
        Parsed fixture object.

    Raises:
        SolarReferenceError: If the fixture or its minimum identity is invalid.
    """
    if not path.is_file():
        raise SolarReferenceError(f"reference fixture is not a file: {path}")
    try:
        parsed: object = json.loads(path.read_text(encoding="utf-8"))
        """Parsed committed JSON without evaluating fixture-controlled code."""
    except json.JSONDecodeError as error:
        raise SolarReferenceError(
            f"reference fixture is invalid JSON: {error}"
        ) from error

    if not isinstance(parsed, dict):
        raise SolarReferenceError("reference fixture must be a JSON object")
    if parsed.get("adapter_contract_version") != CONTRACT_VERSION:
        raise SolarReferenceError(
            f"reference fixture contract must be {CONTRACT_VERSION}"
        )
    if parsed.get("check_id") != check_id:
        raise SolarReferenceError("reference fixture check_id does not match adapter")
    return parsed


def fixture_mapping(fixture: dict[str, object], field: str) -> dict[str, object]:
    """Return one required mapping from a validated fixture envelope.

    Args:
        fixture: Parsed strict fixture envelope.
        field: Required mapping field name.

    Returns:
        The requested heterogeneous JSON mapping.

    Raises:
        SolarReferenceError: If the field is not an object.
    """
    value: object = fixture.get(field)
    """Read one required envelope field without assuming its runtime type."""

    if not isinstance(value, dict):
        raise SolarReferenceError(f"fixture {field} must be an object")
    return value


def require_fixture_inputs(
    fixture: dict[str, object], identities: list[dict[str, str]]
) -> None:
    """Require generated inputs to match the live-refresh identities exactly.

    Args:
        fixture: Parsed strict fixture envelope.
        identities: Identities recomputed from current generated inputs.

    Raises:
        SolarReferenceError: If any generated input changed.
    """
    if fixture.get("input_identities") != identities:
        raise SolarReferenceError("fixture generated-input identities are stale")


def solar_tool_identity() -> list[dict[str, object]]:
    """Probe and return the exact native-SOLAR executable identity.

    Returns:
        One qualified executable record with no separately versioned packages.

    Raises:
        SolarReferenceError: If the executable or banner is unavailable.
    """
    if not SOLAR_EXECUTABLE.is_file():
        raise SolarReferenceError(f"native SOLAR is absent: {SOLAR_EXECUTABLE}")
    completed: subprocess.CompletedProcess[str] = subprocess.run(
        [SOLAR_EXECUTABLE.as_posix()],
        input="exit\n",
        capture_output=True,
        check=False,
        text=True,
    )
    """Started the qualified executable directly and asked its Tcl shell to exit."""

    transcript: str = completed.stdout + completed.stderr
    """Joined both streams because wrapper and native banners can use either."""

    match: re.Match[str] | None = re.search(
        r"SOLAR Eclipse version ([0-9.]+), last updated on ([A-Za-z]+ [0-9]{2}, [0-9]{4})",
        transcript,
    )
    """Located the native release and build date in the startup banner."""

    if match is None:
        raise SolarReferenceError(
            "native SOLAR version banner was not found: " + transcript[-1000:]
        )
    release_date: str = (
        datetime.strptime(match.group(2), "%B %d, %Y").date().isoformat()
    )
    """Normalised the banner date into an unambiguous machine identity."""

    version: str = f"SOLAR Eclipse {match.group(1)} ({release_date})"
    """Combined release number and build date into the qualified version."""

    return [
        {
            "name": SOLAR_EXECUTABLE.as_posix(),
            "version": version,
            "packages": [],
        }
    ]


def require_solar_version(tools: object) -> None:
    """Require the exact native-SOLAR release qualified for these fixtures.

    Args:
        tools: Live or frozen tool identity records.

    Raises:
        SolarReferenceError: If the executable path or version differs.
    """
    if tools != QUALIFIED_SOLAR_TOOLS:
        raise SolarReferenceError(
            f"refresh requires {QUALIFIED_SOLAR_TOOLS!r}, found {tools!r}"
        )


def required_number(text: str, pattern: str, label: str) -> float:
    """Extract one required finite numeric field from native SOLAR output.

    Args:
        text: Native SOLAR report text.
        pattern: Regular expression containing one numeric capture.
        label: Field name used in a fail-closed diagnostic.

    Returns:
        Parsed finite float.

    Raises:
        SolarReferenceError: If SOLAR omitted or malformed the field.
    """
    found: re.Match[str] | None = re.search(pattern, text, re.MULTILINE)
    """Searched the independently generated report for one exact result label."""

    if found is None:
        raise SolarReferenceError(f"SOLAR printed no {label}")
    value: float = float(found.group(1))
    """Converted the captured native decimal into a comparison value."""

    if not math.isfinite(value):
        raise SolarReferenceError(f"SOLAR printed non-finite {label}")
    return value


def required_integer(text: str, pattern: str, label: str) -> int:
    """Extract one required integer field from native SOLAR output.

    Args:
        text: Native SOLAR report text.
        pattern: Regular expression containing one integer capture.
        label: Field name used in a fail-closed diagnostic.

    Returns:
        Parsed integer.

    Raises:
        SolarReferenceError: If SOLAR omitted the field.
    """
    found: re.Match[str] | None = re.search(pattern, text, re.MULTILINE)
    """Searched the independent report for one exact integer result label."""

    if found is None:
        raise SolarReferenceError(f"SOLAR printed no {label}")
    return int(found.group(1))


def check_sex_survived(directory: Path) -> None:
    """Require SOLAR to retain every generated pedigree sex value.

    Args:
        directory: Completed native-SOLAR analysis directory.

    Raises:
        SolarReferenceError: If SOLAR rewrote any sex covariate.
    """
    pedigree_path: Path = directory / "ped.csv"
    """Selected the generated pedigree declaration supplied to native SOLAR."""

    index_path: Path = directory / "pedindex.out"
    """Selected SOLAR's indexed pedigree representation after loading."""

    if not index_path.is_file():
        raise SolarReferenceError("SOLAR produced no pedindex.out sex audit")
    declared: dict[str, str] = {
        line.split(",")[1]: line.split(",")[4]
        for line in pedigree_path.read_text(encoding="utf-8").splitlines()[1:]
    }
    """Indexed the exact generated sex value by native person identifier."""

    matched: set[str] = set()
    """Tracked which declared people were found in the native pedigree index."""

    for line in index_path.read_text(encoding="utf-8").splitlines():
        fields: list[str] = line.split()
        """Parsed one native pedigree-index record."""

        if len(fields) < 8:
            continue
        person: str = fields[-1]
        """Read SOLAR's possibly prefixed person identifier."""

        for name, sex in declared.items():
            if person.endswith(name):
                matched.add(name)
                if fields[3] != sex:
                    raise SolarReferenceError(
                        f"SOLAR reassigned sex for {name} from {sex} to {fields[3]}"
                    )
                break
    """Compared all matched native records with the generated covariate."""

    if matched != set(declared):
        missing: list[str] = sorted(set(declared) - matched)
        """Named generated people absent from the native pedigree audit."""

        raise SolarReferenceError(
            f"SOLAR pedindex omitted {len(missing)} generated people"
        )


def record_list(value: object, label: str) -> list[dict[str, object]]:
    """Validate and return an ordered JSON list of result mappings.

    Args:
        value: Candidate list field.
        label: Source name used in diagnostics.

    Returns:
        Validated list of heterogeneous result mappings.

    Raises:
        SolarReferenceError: If the list shape is invalid.
    """
    if not isinstance(value, list) or not all(item for item in value):
        raise SolarReferenceError(f"{label} records must be a nonempty list")
    if not all(isinstance(item, dict) for item in value):
        raise SolarReferenceError(f"{label} records must all be objects")
    return value


def run_solar(
    directory: Path,
    *,
    command_file: str = "run.tcl",
) -> subprocess.CompletedProcess[str]:
    """Run the qualified native SOLAR executable on one generated command file.

    Args:
        directory: Temporary directory containing generated SOLAR inputs.
        command_file: Tcl command filename inside the temporary directory.

    Returns:
        Captured native process result for adapter-specific parsing.
    """
    command_path: Path = directory / command_file
    """Selected the generated Tcl input without consulting ambient shell state."""

    with command_path.open(encoding="utf-8") as command_stream:
        completed: subprocess.CompletedProcess[str] = subprocess.run(
            [SOLAR_EXECUTABLE.as_posix()],
            stdin=command_stream,
            capture_output=True,
            check=False,
            cwd=directory,
            text=True,
        )
        """Ran native SOLAR without a shell and captured both diagnostic streams."""

    return completed


def emit_reference_record(record: dict[str, object]) -> int:
    """Print one adapter response and return its scientific exit status.

    Args:
        record: Response consumed by the strict fixture driver.

    Returns:
        Zero only when the adapter's prewritten acceptance passed.
    """
    print(json.dumps(record, allow_nan=False, sort_keys=True))
    return 0 if record.get("passed") is True else 1
