"""Compare Asterism's spatial fit against R's `spaMM`, decay rate included.

**The gap this closes.** Every other external comparison in this directory
checks a model at a fixed covariance. The spatial family had none that reached
what makes it spatial. SOLAR cannot: it evaluates the likelihood one pedigree at
a time and silently discards covariance between pedigrees, which is precisely
what a spatial kernel is made of, and `spatial_against_solar.py` asserts that
limitation rather than describing it. So the cross-family covariance and the
estimated decay rate rested on simulation against this package's own generator,
which cannot catch a fault shared by the simulator and the fitter.

`spaMM` reaches both. It fits a Matern spatial random effect beside a supplied
correlation matrix, by REML, and it estimates the range itself rather than
taking it. At `nu = 0.5` the Matern correlation is `exp(-rho * d)`, which is
Asterism's kernel exactly, and spaMM's `rho` is Asterism's decay rate in the
same units. Different language, different author, different optimiser, same
model.

**What the comparison covers, and what it still does not.** It covers the
covariance assembly across families, the REML likelihood, the three variances
and the decay rate. It does not cover the parametric bootstrap, which has no
counterpart in spaMM; that remains simulation against our own generator, and is
recorded as such in `docs/numerical-validation.md`.

**One scenario is generated by `geoR` rather than by us**, so that at least one
case has its field drawn by a third package. The kernel is only `exp(-rho * d)`
and its form is not in doubt, but the *convention* is worth pinning: an
independent generator agreeing with both fitters rules out a shared
misreading of what `rho` scales.

**Locations vary within family on purpose.** Give every sib the same coordinate
and the spatial random effect becomes a family effect, indistinguishable from
the relationship matrix; a first draft of this check did that and both fitters
duly returned nonsense, agreeing with each other all the way. Real geography
crosses families -- relatives live at different addresses -- so the simulation
does too.

Run with:

    uv run --no-project python checks/spatial_against_spamm.py

It needs R with `spaMM` and `geoR` installed, and it fails rather than skips
when either is missing: a check that skips is a check that passes.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

import asterism
import numpy as np

# Both sides stop on their own tolerances, so the agreement is bounded by two
# optimisers rather than by arithmetic. The tolerance is set from what the
# comparison actually achieves, not chosen for comfort.
#
# **The variances are compared as shares of the total, not against themselves.**
# A component resting on nought is where the two implementations differ in kind
# rather than in accuracy: Asterism holds it at exactly nought, because that is
# where the bound is and the projected gradient says so, while spaMM stops a
# hair above. Dividing by a vanishing estimate turns a difference of three
# millionths into a relative difference of one, which says nothing about either
# fit. A share of the trait's variance is the scale a reader cares about.
TOLERANCE = 1e-4

R_SCRIPT = r"""
suppressMessages(library(spaMM))
args <- commandArgs(trailingOnly = TRUE)
here <- args[1]
d <- read.csv(file.path(here, "data.csv"))
A <- as.matrix(read.csv(file.path(here, "A.csv"), header = FALSE))
d$id <- factor(seq_len(nrow(d)))
dimnames(A) <- list(levels(d$id), levels(d$id))
fit <- fitme(y ~ 1 + corrMatrix(1 | id) + Matern(1 | cx + cy),
             corrMatrix = A, fixed = list(nu = 0.5),
             method = "REML", data = d)
out <- list(
  additive = unname(fit$lambda[[1]]),
  spatial = unname(fit$lambda[[2]]),
  residual = unname(fit$phi),
  decay = unname(get_ranPars(fit, which = "corrPars")[["2"]]$rho),
  loglik = unname(fit$APHLs$p_bv)
)
cat(jsonlite::toJSON(out, auto_unbox = TRUE, digits = 15))
"""

GEOR_SCRIPT = r"""
suppressMessages(library(geoR))
args <- commandArgs(trailingOnly = TRUE)
here <- args[1]
spec <- jsonlite::fromJSON(file.path(here, "spec.json"))
set.seed(spec$seed)
coords <- cbind(spec$x, spec$y)
# geoR draws the spatial field itself, from its own exponential covariance.
# `phi` there is a range, so the decay rate is its reciprocal.
field <- grf(nrow(coords), grid = coords, cov.model = "exponential",
             cov.pars = c(spec$spatial, 1 / spec$decay), messages = FALSE)
cat(jsonlite::toJSON(list(field = field$data), auto_unbox = TRUE, digits = 15))
"""


def relationship(families: int, sibs: int) -> np.ndarray:
    """Full sibs in families, the simplest structure that is not the identity."""
    n = families * sibs
    a = np.eye(n)
    for f in range(families):
        index = np.arange(f * sibs, (f + 1) * sibs)
        a[np.ix_(index, index)] = 0.5
        a[index, index] = 1.0
    return a


def run_r(script: str, directory: Path) -> dict:
    path = directory / "script.R"
    path.write_text(script)
    finished = subprocess.run(
        ["Rscript", str(path), str(directory)],
        capture_output=True, text=True, check=False,
    )
    if finished.returncode != 0:
        raise SystemExit(f"R failed:\n{finished.stderr[-3000:]}")
    return json.loads(finished.stdout.strip().splitlines()[-1])


def one(name: str, families: int, sibs: int, truth: dict, seed: int,
        generator: str, directory: Path) -> dict:
    rng = np.random.default_rng(seed)
    n = families * sibs
    a = relationship(families, sibs)
    # One location per person, so the geography crosses the families.
    coordinates = rng.uniform(0.0, 100.0, size=(n, 2))
    distance = np.sqrt(
        ((coordinates[:, None, :] - coordinates[None, :, :]) ** 2).sum(-1)
    )

    if generator == "geoR":
        (directory / "spec.json").write_text(json.dumps({
            "seed": seed, "x": coordinates[:, 0].tolist(),
            "y": coordinates[:, 1].tolist(),
            "spatial": truth["spatial"], "decay": truth["decay"],
        }))
        spatial_part = np.asarray(run_r(GEOR_SCRIPT, directory)["field"])
        genetic = np.linalg.cholesky(
            truth["additive"] * a + 1e-10 * np.eye(n)) @ rng.standard_normal(n)
        residual = np.sqrt(truth["residual"]) * rng.standard_normal(n)
        y = spatial_part + genetic + residual
    else:
        covariance = (
            truth["additive"] * a
            + truth["spatial"] * np.exp(-truth["decay"] * distance)
            + truth["residual"] * np.eye(n)
        )
        y = np.linalg.cholesky(covariance + 1e-10 * np.eye(n)) @ rng.standard_normal(n)

    np.savetxt(directory / "A.csv", a, delimiter=",")
    # `cx` and `cy` rather than `x` and `y`: the response is already `y`, and a
    # second column of that name silently becomes the coordinate R reads.
    np.savetxt(
        directory / "data.csv",
        np.column_stack([y, coordinates]),
        delimiter=",", header="y,cx,cy", comments="", fmt="%.17g",
    )

    theirs = run_r(R_SCRIPT, directory)
    fit = asterism.SpatialModel(
        [np.ascontiguousarray(a)], distance, np.ones((n, 1))
    ).fit(y)
    ours = {
        "additive": fit["variances"][0],
        "spatial": fit["variances"][1],
        "residual": fit["variances"][2],
        "decay": fit["decay_per_km"],
    }

    total = sum(ours[q] for q in ("additive", "spatial", "residual"))

    def difference(quantity: str) -> float:
        gap = abs(ours[quantity] - theirs[quantity])
        if quantity == "decay":
            # No total for a rate to be a share of, so this one is relative.
            return gap / max(abs(theirs[quantity]), 1e-12)
        return gap / max(total, 1e-12)

    worst = max(difference(q) for q in ("additive", "spatial", "residual", "decay"))

    print(f"\n{name}   {n} people, {families} families, generated by {generator}")
    print(f"  {'':<10}{'asterism':>14}{'spaMM':>14}{'difference':>12}{'true':>12}")
    for quantity in ("additive", "spatial", "residual", "decay"):
        print(f"  {quantity:<10}{ours[quantity]:>14.8f}{theirs[quantity]:>14.8f}"
              f"{difference(quantity):>12.2e}{truth[quantity]:>12.4f}")
    print(f"  converged {fit['converged']}, |g| {fit['scaled_gradient']:.2e}, "
          f"polished {fit['polished']}")

    return {
        "scenario": name, "people": n, "families": families,
        "generator": generator, "truth": truth,
        "asterism": ours, "spamm": theirs,
        "worst_difference": worst,
        "converged": bool(fit["converged"]),
        "scaled_gradient": float(fit["scaled_gradient"]),
        "polished": bool(fit["polished"]),
    }


SCENARIOS = [
    # A range well inside the spread of the locations, so it is identified.
    ("a range the data can see", 60, 4,
     {"additive": 0.40, "spatial": 0.30, "residual": 0.30, "decay": 0.08},
     20_260_819, "asterism"),
    # A short range: correlation dies within a few units, so the kernel is
    # close to an identity and the spatial variance is hard to separate from
    # the residual. Both fitters should still land in the same place.
    ("a range shorter than the spacing", 60, 4,
     {"additive": 0.40, "spatial": 0.30, "residual": 0.30, "decay": 1.50},
     20_260_820, "asterism"),
    # A long range: the kernel is nearly constant, which is the degenerate case
    # three GOBS traits fall into. Agreement here is what says a fit at a bound
    # is the data's doing rather than one implementation's.
    ("a range longer than the map", 60, 4,
     {"additive": 0.40, "spatial": 0.30, "residual": 0.30, "decay": 0.002},
     20_260_821, "asterism"),
    # No genetic variance at all, so the spatial component carries everything
    # it is going to carry.
    ("no additive variance", 60, 4,
     {"additive": 0.0001, "spatial": 0.50, "residual": 0.50, "decay": 0.08},
     20_260_822, "asterism"),
    # The field drawn by geoR rather than by us.
    ("a field drawn by geoR", 50, 4,
     {"additive": 0.40, "spatial": 0.30, "residual": 0.30, "decay": 0.08},
     20_260_823, "geoR"),
]


def main() -> int:
    if shutil.which("Rscript") is None:
        raise SystemExit("Rscript is not on the path; this check needs R")
    probe = subprocess.run(
        ["Rscript", "-e",
         'for (p in c("spaMM","geoR","jsonlite")) library(p, character.only=TRUE)'],
        capture_output=True, text=True, check=False,
    )
    if probe.returncode != 0:
        raise SystemExit(
            "R is missing spaMM, geoR or jsonlite. Install them with\n"
            '  Rscript -e \'install.packages(c("spaMM","geoR","jsonlite"))\'\n'
            f"{probe.stderr[-1500:]}"
        )

    print("Asterism's spatial model against R's spaMM, decay rate included.")
    print("At nu = 0.5 the Matern correlation is exp(-rho d), which is our kernel,")
    print("and spaMM's rho is our decay rate in the same units.")

    records = []
    with tempfile.TemporaryDirectory() as raw:
        directory = Path(raw)
        for name, families, sibs, truth, seed, generator in SCENARIOS:
            records.append(one(name, families, sibs, truth, seed, generator, directory))

    worst = max(r["worst_difference"] for r in records)
    print(f"\n{'=' * 74}")
    print(f"worst difference across {len(records)} scenarios and 4 quantities "
          f"each: {worst:.2e}")
    print("\nThis checks that the two implementations agree, not that either")
    print("recovers the truth. The long-range scenario is one neither recovers,")
    print("and they agree on the same wrong answer -- which is what makes it")
    print("evidence about the code rather than about the data.")

    out = (Path(__file__).resolve().parents[1] / "evidence"
           / f"spatial-against-spamm-{date.today().isoformat()}.json")
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps({
        "what": "Asterism's spatial model against R's spaMM, decay rate included",
        "date": date.today().isoformat(),
        "comparator": "spaMM, Matern with nu fixed at 0.5, REML",
        "tolerance": TOLERANCE,
        "difference_is": ("variances as a share of the total, the decay rate "
                          "relative to itself"),
        "worst_difference": worst,
        "scenarios": records,
    }, indent=2) + "\n")
    print(f"written to {out}")

    if worst > TOLERANCE:
        raise SystemExit(
            f"the two implementations differ by {worst:.2e}, above {TOLERANCE:.0e}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
